name: ci
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v3

      - name: Setup pnpm 10.x
      - uses: pnpm/action-setup@v2
        with:
          version: 10.x

      - name: Setup node 20.x
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm run build
